language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile bittorrent/coverage bittorrent/test
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
