language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile coverage bittorrent/test bittorrent/coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
